version: '3.8'
services:

  db:
    image: postgres:15-alpine
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    container_name: work_db
    restart: always

  app:
      build: .
      volumes:
       - .:/work
      ports:
       - 8000:8000
      image : app:work
      container_name: work_container
      command: python manage.py runserver 0.0.0.0:8000
      env_file: .env
      # environment:
      #   - DB_HOST=db
      #   - DB_NAME=work
      #   - DB_USER=postgres
      #   - DB_PASS=password
      depends_on:
        - db

      

# command: sh -c "
#       python manage.py makemigrations
#       && python manage.py migrate  
#       && gunicorn --bind 0.0.0.0:8000 core_app.wsgi"