# Generated by Django 4.1.3 on 2022-11-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kazi',
            name='kazi_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='kazi_id'),
        ),
    ]
