# Generated by Django 4.1.3 on 2022-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0002_alter_kazi_kazi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kazi',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
