# Generated by Django 4.1.3 on 2022-11-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0003_alter_kazi_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaziimages',
            name='image',
        ),
        migrations.AddField(
            model_name='kaziimages',
            name='files',
            field=models.FileField(default='fff', upload_to='kazi/files', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kaziimages',
            name='kazi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kazi.kazi', verbose_name='Kazi Files'),
        ),
    ]
