# Generated by Django 4.1.3 on 2022-11-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0004_remove_kaziimages_image_kaziimages_files_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KaziImages',
            new_name='KaziFiles',
        ),
    ]
