# Generated by Django 4.1.3 on 2022-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0005_rename_kaziimages_kazifiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazi',
            name='terms',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
