# Generated by Django 4.1.3 on 2022-11-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0008_kazi_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazi',
            name='assigned_to',
            field=models.CharField(max_length=50, null=True, verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='kazi',
            name='status',
            field=models.CharField(blank=True, default='UNASSIGNED', max_length=250, null=True),
        ),
    ]
