# Generated by Django 4.1.3 on 2022-11-25 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kazi', '0009_kazi_assigned_to_kazi_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField(verbose_name='Time Due')),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_kazi_assignee', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_kazi_assigner', to=settings.AUTH_USER_MODEL)),
                ('kazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigne_kazi', to='kazi.kazi')),
            ],
        ),
    ]
