# Generated by Django 4.1.3 on 2022-11-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0015_remove_assignee_assigner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kazi',
            name='kazi_id',
        ),
        migrations.AddField(
            model_name='kazi',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='job_id'),
        ),
    ]
