# Generated by Django 4.1.3 on 2022-11-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0016_remove_kazi_kazi_id_kazi_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='kazi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='kazi.kazi'),
        ),
    ]
