# Generated by Django 4.1.3 on 2022-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0018_assignee_status_alter_kazi_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kazi',
            name='assigned_to',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Assignee'),
        ),
    ]
